name: Plane
version: 0.1.2
slug: plane
description: Self-hosted Plane project management for Home Assistant
url: https://github.com/nkcreation/plane-ha-app
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
webui: "http://[HOST]:[PORT:7281]"
ports:
  7281/tcp: 7281
ports_description:
  7281/tcp: Plane Web UI
map:
  - share:rw
  - ssl:ro
panel_icon: mdi:airplane
panel_title: Plane
panel_admin: true
options:
  domain_name: "localhost"
schema:
  domain_name: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
stage: experimental
